// ============================================
// TOOLIEST.COM — Tool Renderers Part 3
// JSON, HTML, JS, Converters, Encoding, Math
// ============================================
const _L = ToolRenderers.layout.bind(ToolRenderers), _S = ToolRenderers.setOutput.bind(ToolRenderers);
const _copySetup = (c) => { const b=c.querySelector('#copy-btn'); if(b) b.addEventListener('click', function(){copyToClipboard(document.getElementById('tool-output').textContent,this)}); };
const _stdTool = (c, label, placeholder, btnText, fn) => { _L(c,`<label>${label}</label><textarea id="tool-input" rows="8" placeholder="${placeholder}"></textarea>`,'',`<button class="btn btn-primary">${btnText}</button>`,fn); _copySetup(c); };

Object.assign(ToolRenderers.renderers, {
  // ===== JSON =====
  'json-formatter'(c) { _stdTool(c,'Paste JSON','{"key":"value"}','✨ Format JSON',()=>{try{_S(JSON.stringify(JSON.parse(document.getElementById('tool-input').value),null,2))}catch(e){_S('Error: '+e.message)}}); },
  'json-validator'(c) { _stdTool(c,'Paste JSON to validate','{"key":"value"}','✅ Validate',()=>{try{JSON.parse(document.getElementById('tool-input').value);_S('✅ Valid JSON!')}catch(e){_S('❌ Invalid JSON:\n'+e.message)}}); },
  'json-minifier'(c) { _stdTool(c,'Paste JSON','{ "key": "value" }','📦 Minify',()=>{try{const m=JSON.stringify(JSON.parse(document.getElementById('tool-input').value));_S(m)}catch(e){_S('Error: '+e.message)}}); },
  'json-to-csv'(c) { _stdTool(c,'Paste JSON Array','[{"name":"John","age":30}]','Convert to CSV',()=>{try{const arr=JSON.parse(document.getElementById('tool-input').value);if(!Array.isArray(arr))throw new Error('Input must be a JSON array');const keys=Object.keys(arr[0]);const csv=[keys.join(','),...arr.map(r=>keys.map(k=>'"'+(r[k]??'')+'"').join(','))].join('\n');_S(csv)}catch(e){_S('Error: '+e.message)}}); },
  'csv-to-json'(c) { _stdTool(c,'Paste CSV Data','name,age\nJohn,30\nJane,25','Convert to JSON',()=>{const lines=document.getElementById('tool-input').value.trim().split('\n');const headers=lines[0].split(',').map(h=>h.trim().replace(/^"|"$/g,''));const json=lines.slice(1).map(line=>{const vals=line.split(',').map(v=>v.trim().replace(/^"|"$/g,''));const obj={};headers.forEach((h,i)=>obj[h]=vals[i]||'');return obj});_S(JSON.stringify(json,null,2))}); },

  // ===== HTML =====
  'html-minifier'(c) { _stdTool(c,'Paste HTML','<div>\n  <p>Hello</p>\n</div>','📦 Minify HTML',()=>{let h=document.getElementById('tool-input').value;const orig=h.length;h=h.replace(/<!--[\s\S]*?-->/g,'').replace(/\s+/g,' ').replace(/>\s+</g,'><').trim();_S(h,{Original:orig+' chars',Minified:h.length+' chars',Saved:((1-h.length/orig)*100).toFixed(1)+'%'})}); },
  'html-beautifier'(c) { _stdTool(c,'Paste Minified HTML','<div><p>Hello</p><span>World</span></div>','✨ Beautify HTML',()=>{let h=document.getElementById('tool-input').value;let indent=0;const result=h.replace(/></g,'>\n<').split('\n').map(line=>{line=line.trim();if(line.match(/^<\//))indent--;const indented='  '.repeat(Math.max(0,indent))+line;if(line.match(/^<[^/!]/)&&!line.match(/\/>/))indent++;return indented}).join('\n');_S(result)}); },
  'html-entity-encoder'(c) {
    c.innerHTML=`<div class="tool-workspace-body"><div class="input-group"><label>Enter text</label><textarea id="tool-input" rows="5" placeholder="<p>Hello & World</p>"></textarea></div><div class="flex gap-2 mb-4"><button class="btn btn-primary" id="he-enc">Encode</button><button class="btn btn-secondary" id="he-dec">Decode</button></div><div class="input-group"><label>Result</label><div class="output-area empty" id="tool-output"><button class="copy-btn hidden" id="copy-btn">Copy</button></div></div></div>`;
    document.getElementById('he-enc').addEventListener('click',()=>{const t=document.getElementById('tool-input').value;const d=document.createElement('div');d.textContent=t;const out=document.getElementById('tool-output'),btn=document.getElementById('copy-btn');out.classList.remove('empty');out.textContent=d.innerHTML;btn.classList.remove('hidden');out.appendChild(btn)});
    document.getElementById('he-dec').addEventListener('click',()=>{const t=document.getElementById('tool-input').value;const d=document.createElement('div');d.innerHTML=t;const out=document.getElementById('tool-output'),btn=document.getElementById('copy-btn');out.classList.remove('empty');out.textContent=d.textContent;btn.classList.remove('hidden');out.appendChild(btn)});
    _copySetup(c);
  },
  'html-table-generator'(c) {
    c.innerHTML=`<div class="tool-workspace-body"><div class="flex gap-4 flex-wrap mb-4"><div class="input-group" style="flex:1"><label>Rows</label><input type="number" id="ht-rows" value="3" min="1" max="20"></div><div class="input-group" style="flex:1"><label>Columns</label><input type="number" id="ht-cols" value="3" min="1" max="10"></div></div><div class="checkbox-group mb-4"><label class="checkbox-label"><input type="checkbox" id="ht-header" checked><span class="checkmark">✓</span> Include Header Row</label><label class="checkbox-label"><input type="checkbox" id="ht-border" checked><span class="checkmark">✓</span> Border</label></div><button class="btn btn-primary mb-4">Generate Table</button><div class="input-group"><label>HTML Code</label><div class="output-area empty" id="tool-output" style="white-space:pre"><button class="copy-btn hidden" id="copy-btn">Copy</button></div></div></div>`;
    c.querySelector('.btn-primary').addEventListener('click',()=>{const rows=+document.getElementById('ht-rows').value,cols=+document.getElementById('ht-cols').value;const hasHeader=document.getElementById('ht-header').checked,hasBorder=document.getElementById('ht-border').checked;let html=`<table${hasBorder?' border="1"':''}>\n`;if(hasHeader){html+='  <thead>\n    <tr>\n';for(let j=1;j<=cols;j++)html+=`      <th>Header ${j}</th>\n`;html+='    </tr>\n  </thead>\n'}html+='  <tbody>\n';for(let i=1;i<=rows;i++){html+='    <tr>\n';for(let j=1;j<=cols;j++)html+=`      <td>Row ${i}, Col ${j}</td>\n`;html+='    </tr>\n'}html+='  </tbody>\n</table>';const out=document.getElementById('tool-output'),btn=document.getElementById('copy-btn');out.classList.remove('empty');out.textContent=html;btn.classList.remove('hidden');out.appendChild(btn)});
    _copySetup(c);
  },
  'markdown-to-html'(c) {
    c.innerHTML=`<div class="tool-workspace-body"><div style="display:grid;grid-template-columns:1fr 1fr;gap:16px"><div class="input-group"><label>Markdown</label><textarea id="md-input" rows="12" placeholder="# Hello\n\n**Bold** and *italic*\n\n- List item 1\n- List item 2"></textarea></div><div class="input-group"><label>Preview</label><div id="md-preview" style="background:var(--bg-secondary);border:1px solid var(--border-color);border-radius:var(--radius-md);padding:16px;min-height:300px;overflow:auto"></div></div></div><div class="input-group mt-4"><label>HTML Output</label><div class="output-area" id="tool-output" style="max-height:200px;overflow:auto"><button class="copy-btn" id="copy-btn">Copy</button></div></div></div>`;
    const convert=()=>{let md=document.getElementById('md-input').value;let html=md.replace(/^### (.*$)/gm,'<h3>$1</h3>').replace(/^## (.*$)/gm,'<h2>$1</h2>').replace(/^# (.*$)/gm,'<h1>$1</h1>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\*(.*?)\*/g,'<em>$1</em>').replace(/`(.*?)`/g,'<code>$1</code>').replace(/^\- (.*$)/gm,'<li>$1</li>').replace(/^\d+\. (.*$)/gm,'<li>$1</li>').replace(/\n\n/g,'</p><p>').replace(/^(?!<[hlu])/gm,'');html='<p>'+html+'</p>';html=html.replace(/<p><\/p>/g,'').replace(/<p>(<h[123]>)/g,'$1').replace(/(<\/h[123]>)<\/p>/g,'$1');document.getElementById('md-preview').innerHTML=html;const out=document.getElementById('tool-output'),btn=document.getElementById('copy-btn');out.textContent=html;out.appendChild(btn)};
    document.getElementById('md-input').addEventListener('input',convert);_copySetup(c);convert();
  },

  // ===== JAVASCRIPT =====
  'js-minifier'(c) { _stdTool(c,'Paste JavaScript','function hello() {\n  console.log("world");\n}','📦 Minify JS',()=>{let js=document.getElementById('tool-input').value;const orig=js.length;js=js.replace(/\/\*[\s\S]*?\*\//g,'').replace(/\/\/.*$/gm,'').replace(/\s+/g,' ').replace(/\s*([{}();,=+\-*/<>!&|?:])\s*/g,'$1').trim();_S(js,{Original:orig+' chars',Minified:js.length+' chars',Saved:((1-js.length/orig)*100).toFixed(1)+'%'})}); },
  'js-beautifier'(c) { _stdTool(c,'Paste Minified JS','function hello(){console.log("world")}','✨ Beautify JS',()=>{let js=document.getElementById('tool-input').value;let indent=0;let result='';for(let i=0;i<js.length;i++){const ch=js[i];if(ch==='{'){indent++;result+=' {\n'+'  '.repeat(indent)}else if(ch==='}'){indent--;result+='\n'+'  '.repeat(indent)+'}'}else if(ch===';'){result+=';\n'+'  '.repeat(indent)}else{result+=ch}}_S(result.trim())}); },
  'regex-tester'(c) {
    c.innerHTML=`<div class="tool-workspace-body"><div class="flex gap-4 flex-wrap mb-4"><div class="input-group" style="flex:3"><label>Regular Expression</label><input type="text" id="rx-pattern" placeholder="[a-z]+"></div><div class="input-group" style="flex:1;min-width:80px"><label>Flags</label><input type="text" id="rx-flags" value="gi" placeholder="gi"></div></div><div class="input-group"><label>Test String</label><textarea id="rx-input" rows="5" placeholder="Enter text to test against...">Hello World 123 foo@bar.com</textarea></div><div class="input-group mt-4"><label>Matches</label><div class="output-area" id="tool-output">Enter a regex pattern above</div></div></div>`;
    const test=()=>{try{const pattern=document.getElementById('rx-pattern').value;const flags=document.getElementById('rx-flags').value;const text=document.getElementById('rx-input').value;if(!pattern)return;const regex=new RegExp(pattern,flags);const matches=[...text.matchAll(new RegExp(pattern,flags.includes('g')?flags:flags+'g'))];const out=document.getElementById('tool-output');if(matches.length){out.innerHTML=`<strong style="color:var(--accent-success)">${matches.length} match(es) found:</strong>\n\n`+matches.map((m,i)=>`Match ${i+1}: "${m[0]}" at index ${m.index}`).join('\n')}else{out.textContent='No matches found.'}}catch(e){document.getElementById('tool-output').textContent='Error: '+e.message}};
    ['rx-pattern','rx-flags','rx-input'].forEach(id=>document.getElementById(id).addEventListener('input',test));test();
  },
  'js-obfuscator'(c) { _stdTool(c,'Paste JavaScript','var x = "hello";','🔒 Obfuscate',()=>{const js=document.getElementById('tool-input').value;const obf=js.replace(/var\s+(\w+)/g,(_,v)=>'var _0x'+Math.random().toString(16).substr(2,4)).replace(/"([^"]*)"/g,(m,s)=>{const codes=s.split('').map(c=>'\\x'+c.charCodeAt(0).toString(16).padStart(2,'0')).join('');return'"'+codes+'"'}).replace(/console\.log/g,'window["console"]["log"]');_S(obf)}); },

  // ===== CONVERTERS =====
  'unit-converter'(c) {
    const units={Length:{m:1,km:1000,cm:0.01,mm:0.001,mi:1609.34,yd:0.9144,ft:0.3048,in:0.0254},Weight:{kg:1,g:0.001,mg:0.000001,lb:0.453592,oz:0.0283495,ton:1000},Volume:{l:1,ml:0.001,gal:3.78541,qt:0.946353,cup:0.236588,fl_oz:0.0295735}};
    c.innerHTML=`<div class="tool-workspace-body"><div class="input-group"><label>Category</label><select id="uc-cat">${Object.keys(units).map(k=>`<option>${k}</option>`).join('')}</select></div><div class="flex gap-4 flex-wrap"><div class="input-group" style="flex:1"><label>Value</label><input type="number" id="uc-val" value="1"></div><div class="input-group" style="flex:1"><label>From</label><select id="uc-from"></select></div><div class="input-group" style="flex:1"><label>To</label><select id="uc-to"></select></div></div><div class="stat-card mt-4 text-center"><div class="stat-num" id="uc-result">1</div><div class="stat-lbl" id="uc-label">Result</div></div></div>`;
    const fillUnits=()=>{const cat=document.getElementById('uc-cat').value;const keys=Object.keys(units[cat]);['uc-from','uc-to'].forEach((id,i)=>{document.getElementById(id).innerHTML=keys.map((k,j)=>`<option${j===i?' selected':''}>${k}</option>`).join('')});convert()};
    const convert=()=>{const cat=document.getElementById('uc-cat').value;const val=+document.getElementById('uc-val').value;const from=document.getElementById('uc-from').value;const to=document.getElementById('uc-to').value;const result=(val*units[cat][from]/units[cat][to]).toFixed(6);document.getElementById('uc-result').textContent=result;document.getElementById('uc-label').textContent=`${val} ${from} = ${result} ${to}`};
    document.getElementById('uc-cat').addEventListener('change',fillUnits);['uc-val','uc-from','uc-to'].forEach(id=>document.getElementById(id).addEventListener('input',convert));fillUnits();
  },
  'temperature-converter'(c) {
    c.innerHTML=`<div class="tool-workspace-body"><div class="input-group"><label>Temperature Value</label><input type="number" id="tc-val" value="100"></div><div class="result-stats mt-4" id="tc-results"></div></div>`;
    const update=()=>{const v=+document.getElementById('tc-val').value;const c2f=v*9/5+32;const c2k=v+273.15;const f2c=(v-32)*5/9;const f2k=(v-32)*5/9+273.15;const k2c=v-273.15;const k2f=(v-273.15)*9/5+32;document.getElementById('tc-results').innerHTML=[['°C → °F',c2f.toFixed(2)+'°F'],['°C → K',c2k.toFixed(2)+'K'],['°F → °C',f2c.toFixed(2)+'°C'],['°F → K',f2k.toFixed(2)+'K'],['K → °C',k2c.toFixed(2)+'°C'],['K → °F',k2f.toFixed(2)+'°F']].map(([l,v])=>`<div class="stat-card"><div class="stat-num" style="font-size:1rem">${v}</div><div class="stat-lbl">${l}</div></div>`).join('')};
    document.getElementById('tc-val').addEventListener('input',update);update();
  },
  'number-base-converter'(c) {
    c.innerHTML=`<div class="tool-workspace-body"><div class="input-group"><label>Enter a Number</label><input type="text" id="nb-input" value="255" placeholder="255"></div><div class="input-group"><label>Input Base</label><select id="nb-base"><option value="10" selected>Decimal (10)</option><option value="2">Binary (2)</option><option value="8">Octal (8)</option><option value="16">Hexadecimal (16)</option></select></div><div class="color-values mt-4" id="nb-results"></div></div>`;
    const update=()=>{try{const val=document.getElementById('nb-input').value;const base=+document.getElementById('nb-base').value;const dec=parseInt(val,base);document.getElementById('nb-results').innerHTML=[['Decimal',dec.toString(10)],['Binary',dec.toString(2)],['Octal',dec.toString(8)],['Hex','0x'+dec.toString(16).toUpperCase()]].map(([l,v])=>`<div class="color-value-item" style="cursor:pointer" onclick="copyToClipboard('${v}')"><span>${l}</span><span>${v}</span></div>`).join('')}catch(e){}};
    ['nb-input','nb-base'].forEach(id=>document.getElementById(id).addEventListener('input',update));update();
  },
  'timezone-converter'(c) {
    const zones=['UTC','America/New_York','America/Chicago','America/Denver','America/Los_Angeles','Europe/London','Europe/Paris','Europe/Berlin','Asia/Tokyo','Asia/Shanghai','Asia/Kolkata','Asia/Kathmandu','Australia/Sydney','Pacific/Auckland'];
    c.innerHTML=`<div class="tool-workspace-body"><div class="flex gap-4 flex-wrap"><div class="input-group" style="flex:1"><label>Time</label><input type="text" id="tz-time" value="${new Date().toTimeString().slice(0,5)}" placeholder="14:30"></div><div class="input-group" style="flex:1"><label>From</label><select id="tz-from">${zones.map(z=>`<option${z==='UTC'?' selected':''}>${z}</option>`).join('')}</select></div></div><div class="mt-4" id="tz-results"></div></div>`;
    const update=()=>{const timeStr=document.getElementById('tz-time').value;const results=zones.map(zone=>{try{const now=new Date();const [h,m]=timeStr.split(':').map(Number);now.setHours(h,m,0,0);const converted=now.toLocaleTimeString('en-US',{timeZone:zone,hour:'2-digit',minute:'2-digit',hour12:true});return`<div class="color-value-item"><span>${zone.split('/').pop().replace(/_/g,' ')}</span><span>${converted}</span></div>`}catch(e){return''}}).join('');document.getElementById('tz-results').innerHTML='<div class="color-values" style="grid-template-columns:repeat(auto-fit,minmax(200px,1fr))">'+results+'</div>'};
    ['tz-time','tz-from'].forEach(id=>document.getElementById(id).addEventListener('input',update));update();
  },

  // ===== ENCODING =====
  'base64-encoder'(c) {
    c.innerHTML=`<div class="tool-workspace-body"><div class="input-group"><label>Enter text</label><textarea id="tool-input" rows="5" placeholder="Hello World"></textarea></div><div class="flex gap-2 mb-4"><button class="btn btn-primary" id="b64-enc">Encode</button><button class="btn btn-secondary" id="b64-dec">Decode</button></div><div class="input-group"><label>Result</label><div class="output-area empty" id="tool-output"><button class="copy-btn hidden" id="copy-btn">Copy</button></div></div></div>`;
    document.getElementById('b64-enc').addEventListener('click',()=>{try{const r=btoa(unescape(encodeURIComponent(document.getElementById('tool-input').value)));const o=document.getElementById('tool-output'),b=document.getElementById('copy-btn');o.classList.remove('empty');o.textContent=r;b.classList.remove('hidden');o.appendChild(b)}catch(e){document.getElementById('tool-output').textContent='Error: '+e.message}});
    document.getElementById('b64-dec').addEventListener('click',()=>{try{const r=decodeURIComponent(escape(atob(document.getElementById('tool-input').value)));const o=document.getElementById('tool-output'),b=document.getElementById('copy-btn');o.classList.remove('empty');o.textContent=r;b.classList.remove('hidden');o.appendChild(b)}catch(e){document.getElementById('tool-output').textContent='Error: Invalid Base64'}});
    _copySetup(c);
  },
  'url-encoder'(c) {
    c.innerHTML=`<div class="tool-workspace-body"><div class="input-group"><label>Enter URL or text</label><textarea id="tool-input" rows="4" placeholder="https://example.com/path?q=hello world&lang=en"></textarea></div><div class="flex gap-2 mb-4"><button class="btn btn-primary" id="ue-enc">Encode</button><button class="btn btn-secondary" id="ue-dec">Decode</button></div><div class="input-group"><label>Result</label><div class="output-area empty" id="tool-output"><button class="copy-btn hidden" id="copy-btn">Copy</button></div></div></div>`;
    const show=(text)=>{const o=document.getElementById('tool-output'),b=document.getElementById('copy-btn');o.classList.remove('empty');o.textContent=text;b.classList.remove('hidden');o.appendChild(b)};
    document.getElementById('ue-enc').addEventListener('click',()=>show(encodeURIComponent(document.getElementById('tool-input').value)));
    document.getElementById('ue-dec').addEventListener('click',()=>{try{show(decodeURIComponent(document.getElementById('tool-input').value))}catch(e){show('Error: '+e.message)}});
    _copySetup(c);
  },
  'jwt-decoder'(c) { _stdTool(c,'Paste JWT Token','eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIn0.xxx','🔓 Decode JWT',()=>{const jwt=document.getElementById('tool-input').value.trim();const parts=jwt.split('.');if(parts.length!==3){_S('Error: JWT must have 3 parts');return}try{const header=JSON.parse(atob(parts[0]));const payload=JSON.parse(atob(parts[1]));_S('=== HEADER ===\n'+JSON.stringify(header,null,2)+'\n\n=== PAYLOAD ===\n'+JSON.stringify(payload,null,2)+'\n\n=== SIGNATURE ===\n'+parts[2])}catch(e){_S('Error decoding: '+e.message)}}); },
  'hash-generator'(c) {
    c.innerHTML=`<div class="tool-workspace-body"><div class="input-group"><label>Enter text to hash</label><textarea id="tool-input" rows="4" placeholder="Hello World"></textarea></div><button class="btn btn-primary mb-4" id="hash-gen">Generate Hashes</button><div class="color-values" id="hash-results"></div></div>`;
    document.getElementById('hash-gen').addEventListener('click',async()=>{const text=document.getElementById('tool-input').value;const encoder=new TextEncoder();const data=encoder.encode(text);const algos=['SHA-1','SHA-256','SHA-384','SHA-512'];const results=[];for(const algo of algos){const hash=await crypto.subtle.digest(algo,data);const hex=Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('');results.push([algo,hex])}document.getElementById('hash-results').innerHTML=results.map(([l,v])=>`<div class="color-value-item" style="cursor:pointer;grid-column:1/-1" onclick="copyToClipboard('${v}')"><span>${l}</span><span style="font-size:0.75rem;word-break:break-all">${v}</span></div>`).join('')});
  },

  // ===== MATH =====
  'percentage-calculator'(c) {
    c.innerHTML=`<div class="tool-workspace-body"><h3 style="font-size:0.95rem;margin-bottom:16px;color:var(--text-secondary)">What is X% of Y?</h3><div class="flex gap-4 flex-wrap mb-4"><div class="input-group" style="flex:1"><label>Percentage (%)</label><input type="number" id="pc-pct" value="25"></div><div class="input-group" style="flex:1"><label>Of Number</label><input type="number" id="pc-num" value="200"></div></div><div class="stat-card text-center mb-4"><div class="stat-num" id="pc-r1">50</div><div class="stat-lbl" id="pc-l1">25% of 200 = 50</div></div><h3 style="font-size:0.95rem;margin-bottom:16px;margin-top:24px;color:var(--text-secondary)">Percentage Change</h3><div class="flex gap-4 flex-wrap"><div class="input-group" style="flex:1"><label>From</label><input type="number" id="pc-from" value="100"></div><div class="input-group" style="flex:1"><label>To</label><input type="number" id="pc-to" value="150"></div></div><div class="stat-card text-center mt-4"><div class="stat-num" id="pc-r2">50%</div><div class="stat-lbl">Percentage Change</div></div></div>`;
    const update=()=>{const pct=+document.getElementById('pc-pct').value,num=+document.getElementById('pc-num').value;const r=pct/100*num;document.getElementById('pc-r1').textContent=r;document.getElementById('pc-l1').textContent=`${pct}% of ${num} = ${r}`;const from=+document.getElementById('pc-from').value,to=+document.getElementById('pc-to').value;const change=((to-from)/from*100).toFixed(2);document.getElementById('pc-r2').textContent=change+'%'};
    ['pc-pct','pc-num','pc-from','pc-to'].forEach(id=>document.getElementById(id).addEventListener('input',update));update();
  },
  'age-calculator'(c) {
    c.innerHTML=`<div class="tool-workspace-body"><div class="input-group"><label>Date of Birth</label><input type="date" id="ac-dob" value="1995-01-15"></div><div class="result-stats mt-4" id="ac-results"></div></div>`;
    const update=()=>{const dob=new Date(document.getElementById('ac-dob').value);const now=new Date();let years=now.getFullYear()-dob.getFullYear();let months=now.getMonth()-dob.getMonth();let days=now.getDate()-dob.getDate();if(days<0){months--;days+=new Date(now.getFullYear(),now.getMonth(),0).getDate()}if(months<0){years--;months+=12}const totalDays=Math.floor((now-dob)/(1000*60*60*24));const nextBday=new Date(now.getFullYear(),dob.getMonth(),dob.getDate());if(nextBday<now)nextBday.setFullYear(nextBday.getFullYear()+1);const daysToNext=Math.ceil((nextBday-now)/(1000*60*60*24));document.getElementById('ac-results').innerHTML=[['Years',years],['Months',months],['Days',days],['Total Days',totalDays.toLocaleString()],['Next Birthday',daysToNext+' days']].map(([l,v])=>`<div class="stat-card"><div class="stat-num">${v}</div><div class="stat-lbl">${l}</div></div>`).join('')};
    document.getElementById('ac-dob').addEventListener('input',update);update();
  },
  'bmi-calculator'(c) {
    c.innerHTML=`<div class="tool-workspace-body"><div class="flex gap-4 flex-wrap"><div class="input-group" style="flex:1"><label>Weight (kg)</label><input type="number" id="bmi-w" value="70" min="1"></div><div class="input-group" style="flex:1"><label>Height (cm)</label><input type="number" id="bmi-h" value="175" min="1"></div></div><div class="stat-card text-center mt-4"><div class="stat-num" id="bmi-val">22.9</div><div class="stat-lbl" id="bmi-cat">Normal weight</div></div><div class="mt-4" id="bmi-bar"></div></div>`;
    const update=()=>{const w=+document.getElementById('bmi-w').value,h=+document.getElementById('bmi-h').value/100;const bmi=(w/(h*h)).toFixed(1);let cat='',color='';if(bmi<18.5){cat='Underweight';color='#06b6d4'}else if(bmi<25){cat='Normal weight';color='#10b981'}else if(bmi<30){cat='Overweight';color='#f59e0b'}else{cat='Obese';color='#f43f5e'}document.getElementById('bmi-val').textContent=bmi;document.getElementById('bmi-val').style.color=color;document.getElementById('bmi-cat').textContent=cat;document.getElementById('bmi-bar').innerHTML=`<div style="height:8px;background:var(--bg-tertiary);border-radius:99px;position:relative"><div style="position:absolute;left:${Math.min(95,Math.max(0,(bmi/40)*100))}%;top:-4px;width:16px;height:16px;background:${color};border-radius:50%;transform:translateX(-50%)"></div></div><div class="flex justify-between mt-2" style="font-size:0.7rem;color:var(--text-tertiary)"><span>Underweight</span><span>Normal</span><span>Overweight</span><span>Obese</span></div>`};
    ['bmi-w','bmi-h'].forEach(id=>document.getElementById(id).addEventListener('input',update));update();
  },

  'tip-calculator'(c) {
    c.innerHTML=`<div class="tool-workspace-body"><div class="flex gap-4 flex-wrap"><div class="input-group" style="flex:1"><label>Bill Amount ($)</label><input type="number" id="tip-bill" value="85.50"></div><div class="input-group" style="flex:1"><label>Tip: <span id="tip-pct-val">18</span>%</label><input type="range" id="tip-pct" min="0" max="50" value="18"></div><div class="input-group" style="flex:1"><label>Split Between</label><input type="number" id="tip-split" value="2" min="1"></div></div><div class="result-stats mt-4" id="tip-results"></div></div>`;
    const update=()=>{const bill=+document.getElementById('tip-bill').value;const pct=+document.getElementById('tip-pct').value;const split=+document.getElementById('tip-split').value;document.getElementById('tip-pct-val').textContent=pct;const tip=bill*pct/100;const total=bill+tip;document.getElementById('tip-results').innerHTML=[['Tip Amount','$'+tip.toFixed(2)],['Total','$'+total.toFixed(2)],['Per Person','$'+(total/split).toFixed(2)],['Tip/Person','$'+(tip/split).toFixed(2)]].map(([l,v])=>`<div class="stat-card"><div class="stat-num" style="font-size:1.1rem">${v}</div><div class="stat-lbl">${l}</div></div>`).join('')};
    ['tip-bill','tip-pct','tip-split'].forEach(id=>document.getElementById(id).addEventListener('input',update));update();
  },
});
